### ISSUE TITLE
All .otf files are malfunctioning

### ISSUE THREAD

**Issue by emeraldragon10005** [slavonic/slavonic.github.io#8]
This [website](https://sci.ponomar.net/fonts.html) (which redirects to your Github) does not have any functioning Slavonic fonts. They all appear like so when opening them:

![image](https://github.com/user-attachments/assets/f4466287-121f-4811-867c-c1ff6065dfa9)

**Comment by typiconman** [comment]
The OTF fonts work fine. This is the default Windows preview window (it shows the Latin character set and the default test phrase).

There is a way to specify our own Sample Text in the fonts, but it doesn't seem to be honored by the preview programs anyway.

**Comment by typiconman** [comment]
Closed as invalid.
